safe:        true
port:        4000
baseurl:     /
url:         http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date
