safe: true
lsi: false
source: .
name: siejkowski.net 
author: krzysztof siejkowski
deployurl: http://siejkowski.net

future: true
permalink: :title

exclude: [CNAME, Gemfile, Gemfile.lock, README.md]

highlighter: pygments
markdown: kramdown

